name: noaharvester
services:
  app:
    image: noaharvester:latest
    build:
      context: .
      secrets:
        - COPERNICUS_LOGIN
        - COPERNICUS_PASSWORD
        - EARTHDATA_LOGIN
        - EARTHDATA_PASSWORD
    working_dir: /app    
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    command: python /app/noaharvester/cli.py --help

secrets:
  COPERNICUS_LOGIN:
    environment: COPERNICUS_LOGIN
  COPERNICUS_PASSWORD:
    environment: COPERNICUS_PASSWORD
  EARTHDATA_LOGIN:
    environment: EARTHDATA_LOGIN
  EARTHDATA_PASSWORD:
    environment: EARTHDATA_PASSWORD