name: noaharvester
services:
  noaharvester:
    image: noaharvester:latest
    build:
      context: .
      secrets:
        - COPERNICUS_LOGIN
        - COPERNICUS_PASSWORD
        - EARTHDATA_LOGIN
        - EARTHDATA_PASSWORD
        - DB_USER
        - DB_PASSWORD
        - DB_HOST
        - DB_PORT
        - DB_NAME
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9092,kafka3:9092"
    working_dir: /app    
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    command: python /app/noaharvester/cli.py --help

secrets:
  COPERNICUS_LOGIN:
    environment: COPERNICUS_LOGIN
  COPERNICUS_PASSWORD:
    environment: COPERNICUS_PASSWORD
  EARTHDATA_LOGIN:
    environment: EARTHDATA_LOGIN
  EARTHDATA_PASSWORD:
    environment: EARTHDATA_PASSWORD
  DB_USER:
    environment: DB_USER
  DB_PASSWORD:
    environment: DB_PASSWORD
  DB_HOST:
    environment: DB_HOST
  DB_PORT:
    environment: DB_PORT
  DB_NAME:
    environment: DB_NAME