name: noachdm
services:
  noacdm:
    image: noachdm:latest
    build:
      context: .
      secrets:
        - CREODIAS_S3_ACCESS_KEY
        - CREODIAS_S3_SECRET_KEY
        - CREODIAS_REGION
        - CREODIAS_ENDPOINT
        - CREODIAS_S3_BUCKET_PRODUCT_OUTPUT
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9092,kafka3:9092"
    working_dir: /app    
    volumes:
      - ./config:/app/config
    command: python /app/noachdm/cli.py --help

secrets:
  CREODIAS_S3_ACCESS_KEY:
    environment: CREODIAS_S3_ACCESS_KEY
  CREODIAS_S3_SECRET_KEY:
    environment: CREODIAS_S3_SECRET_KEY
  CREODIAS_REGION:
    environment: CREODIAS_REGION
  CREODIAS_ENDPOINT:
    environment: CREODIAS_ENDPOINT
  CREODIAS_S3_BUCKET_PRODUCT_OUTPUT:
    environment: CREODIAS_S3_BUCKET_PRODUCT_OUTPUT