version: '3.8'

services:
  app:
    image: cdsetool-cli:latest
    build: .
    env_file:
      - path: ./.env.list
        required: true # default
    volumes:
      - ./config:/app/config
      - ./data:/app/data